version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - ../web:/var/www/html
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ../secrets:/etc/secrets
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - inception_network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - ../web:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${DATABASE_HOST}:${DATABASE_PORT}
      - WORDPRESS_DB_USER=${DATABASE_USER}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD}
      - WORDPRESS_DB_NAME=${DATABASE_NAME}
    networks:
      - inception_network
    restart: always

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  web:
    driver: local
